[package]
name = "hello_rust_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
jsonwebtoken = "8"
serde = {version = "1.0", features = ["derive"] }
http = "0.1"
vercel_lambda = "*"
